export const PLANTS = [
  // TERRACE - Wall 2 (west fence, wisteria)
  {
    id: 'wisteria-left',
    name: 'Wisteria',
    species: 'Wisteria sinensis',
    wall: 2,
    position: { x: 0.06, y: 0.35 },
    health: 'thriving',
    emoji: '🌸',
    personality: 'dramatic',
    container: 'Wooden barrel planter',
    lore: 'Established and ambitious. Already climbing the diamond wire grid that spans the cedar fence. This wisteria has been here longer than you — it has opinions about the wall.',
    poem: 'I have claimed\nthe fence, the wires, the light.\nPrune me. I dare you.',
    nextCare: 'Train new canes to wires',
    daysOverdue: 0,
    season: 'dormant-waking',
  },
  {
    id: 'wisteria-right',
    name: 'Wisteria',
    species: 'Wisteria sinensis',
    wall: 2,
    position: { x: 0.06, y: 0.65 },
    health: 'thriving',
    emoji: '🌸',
    personality: 'dramatic',
    container: 'Wooden barrel planter',
    lore: 'The other half of the wisteria symmetry flanking the couch. Equally ambitious, slightly more patient. Together they are planning something.',
    poem: 'My sister reaches left.\nI reach right.\nBetween us: the couch, the fire, the years.',
    nextCare: 'Train new canes to wires',
    daysOverdue: 0,
    season: 'dormant-waking',
  },

  // TERRACE - Wall 2/3 corner evergreen
  {
    id: 'evergreen-1',
    name: 'Evergreen',
    species: 'Thuja occidentalis',
    wall: 'corner-23',
    position: { x: 0.14, y: 0.08 },
    health: 'thriving',
    emoji: '🌲',
    personality: 'steadfast',
    container: 'White ribbed cylinder',
    lore: 'The sentinel of the Wall 2/3 corner. Green all winter, green all summer. Asks for little. Gives constant background beauty.',
    poem: 'I was green in January.\nI will be green in July.\nI am the punctuation of this garden.',
    nextCare: 'Light trim if needed',
    daysOverdue: 0,
    season: 'evergreen',
  },

  // TERRACE - Wall 3 (Zéphirine + lavender)
  {
    id: 'zephirine',
    name: 'Zéphirine Drouhin',
    species: 'Rosa Zéphirine Drouhin',
    wall: 3,
    position: { x: 0.38, y: 0.07 },
    health: 'content',
    emoji: '🌹',
    personality: 'theatrical',
    container: 'Cedar raised planter (left)',
    lore: 'A thornless climbing rose of deep pink, extraordinary fragrance, and theatrical bearing. Named for Zéphirin Drouhin, a Burgundy wine merchant. She climbs the lattice on Wall 3 and intends to keep climbing.',
    poem: 'Thornless, they say,\nas if softness were not\nits own kind of power.',
    nextCare: 'Neem oil application',
    daysOverdue: 3,
    season: 'dormant-waking',
  },
  {
    id: 'lavender',
    name: 'Lavender',
    species: 'Lavandula angustifolia',
    wall: 3,
    position: { x: 0.42, y: 0.07 },
    health: 'content',
    emoji: '💜',
    personality: 'calm',
    container: 'Cedar raised planter (left, center)',
    lore: 'Planted in the center of the Zéphirine\'s planter as a companion. Lavender confuses aphids and deters them from the rose. It is also simply pleasant. Silver-green foliage, already showing signs of life.',
    poem: 'The rose gets the poems.\nI get the bees.\nWe are both content.',
    nextCare: 'Light trim of old growth',
    daysOverdue: 0,
    season: 'dormant-waking',
  },
  {
    id: 'rose-wall3',
    name: 'Climbing Rose',
    species: 'Rosa (climbing)',
    wall: 3,
    position: { x: 0.58, y: 0.07 },
    health: 'content',
    emoji: '🌹',
    personality: 'steady',
    container: 'Cedar raised planter (right)',
    lore: 'The second climbing rose on Wall 3, training up the right lattice panel. A steady presence alongside the more flamboyant Zéphirine.',
    poem: 'I am not the famous one.\nBut I bloom, and bloom again,\nand that is enough.',
    nextCare: 'Neem oil application',
    daysOverdue: 3,
    season: 'dormant-waking',
  },

  // TERRACE - Wall 3/4 corner evergreen
  {
    id: 'evergreen-2',
    name: 'Evergreen',
    species: 'Thuja occidentalis',
    wall: 'corner-34',
    position: { x: 0.86, y: 0.08 },
    health: 'thriving',
    emoji: '🌲',
    personality: 'steadfast',
    container: 'White ribbed cylinder',
    lore: 'Mirror of Evergreen #1 at the other corner of Wall 3. These two bookend the garden\'s northern wall with quiet permanence.',
    poem: 'Across the wall, my twin.\nWe have not spoken.\nWe do not need to.',
    nextCare: 'Light trim if needed',
    daysOverdue: 0,
    season: 'evergreen',
  },

  // TERRACE - Wall 4 (the lineup)
  {
    id: 'evergreen-wall4-left',
    name: 'Evergreen',
    species: 'Thuja occidentalis',
    wall: 4,
    position: { x: 0.88, y: 0.22 },
    health: 'thriving',
    emoji: '🌲',
    personality: 'steadfast',
    container: 'White ribbed cylinder',
    lore: 'The first sentinel of the Wall 4 lineup. Green, columnar, reliable.',
    poem: 'First in line.\nNo complaints.',
    nextCare: 'None needed',
    daysOverdue: 0,
    season: 'evergreen',
  },
  {
    id: 'serviceberry',
    name: 'Serviceberry',
    species: 'Amelanchier',
    wall: 4,
    position: { x: 0.88, y: 0.35 },
    health: 'thriving',
    emoji: '🌳',
    personality: 'sentimental',
    container: 'Grey glazed cylinder',
    lore: 'A wedding gift for Emma. Planted in the first spring here. Its coral-red branches glow in winter like a quiet reminder of what matters. In spring it will bloom white. In summer, small purple berries for birds.',
    poem: 'She planted me\nthe year they married.\nI remember everything.',
    nextCare: 'Watch for first buds',
    daysOverdue: 0,
    season: 'dormant-waking',
    special: 'wedding-gift',
  },
  {
    id: 'hydrangea-1',
    name: 'Pinnacle Lime Hydrangea',
    species: 'Hydrangea paniculata "Limelight"',
    wall: 4,
    position: { x: 0.88, y: 0.48 },
    health: 'content',
    emoji: '💐',
    personality: 'cheerful',
    container: 'Large grey round pot',
    lore: 'First of three Pinnacle Lime hydrangeas along Wall 4. Still holding its papery dried flower heads from last season — a lovely ghost of summer past. Ready for pruning.',
    poem: 'My old flowers hang on\nlike stories no one\nhas asked me to stop telling.',
    nextCare: 'Prune to 1/3 height',
    daysOverdue: 5,
    season: 'dormant',
  },
  {
    id: 'hydrangea-2',
    name: 'Pinnacle Lime Hydrangea',
    species: 'Hydrangea paniculata "Limelight"',
    wall: 4,
    position: { x: 0.88, y: 0.58 },
    health: 'content',
    emoji: '💐',
    personality: 'cheerful',
    container: 'Large grey round pot',
    lore: 'Middle hydrangea. Gossips with the other two constantly.',
    poem: 'Did you hear\nwhat the serviceberry said?\nNeither did I. But still.',
    nextCare: 'Prune to 1/3 height',
    daysOverdue: 5,
    season: 'dormant',
  },
  {
    id: 'hydrangea-3',
    name: 'Pinnacle Lime Hydrangea',
    species: 'Hydrangea paniculata "Limelight"',
    wall: 4,
    position: { x: 0.88, y: 0.68 },
    health: 'content',
    emoji: '💐',
    personality: 'cheerful',
    container: 'Large grey round pot',
    lore: 'Third hydrangea. Closest to the Japanese maple and perhaps influenced by it.',
    poem: 'The maple is so quiet.\nI have been trying\nto learn from this.',
    nextCare: 'Prune to 1/3 height',
    daysOverdue: 5,
    season: 'dormant',
  },
  {
    id: 'japanese-maple',
    name: 'Japanese Maple',
    species: 'Acer palmatum',
    wall: 4,
    position: { x: 0.88, y: 0.78 },
    health: 'thriving',
    emoji: '🍁',
    personality: 'contemplative',
    container: 'Grey glazed pot',
    lore: 'A gift from a friend. Delicate, fine-branching, speaks quietly. In autumn its leaves turn a deep crimson that seems almost deliberate. Has been through one winter here and seems to have made peace with Brooklyn.',
    poem: 'A friend carried me here.\nI have been thinking about that\never since.',
    nextCare: 'Watch for first leaf buds',
    daysOverdue: 0,
    season: 'dormant-waking',
    special: 'friends-gift',
  },
  {
    id: 'evergreen-christmas',
    name: 'Christmas Tree',
    species: 'Thuja occidentalis',
    wall: 'corner-41',
    position: { x: 0.88, y: 0.88 },
    health: 'recovering',
    emoji: '🎄',
    personality: 'resilient',
    container: 'White ribbed cylinder',
    lore: 'This evergreen served as the Christmas tree indoors this winter. It was decorated, admired, and then returned to the terrace in January. It is adjusting. A few ornaments still hang from it — nobody has quite gotten around to removing them.',
    poem: 'I was decorated.\nThen I was outside again.\nBoth were fine.',
    nextCare: 'Water generously — recovery mode',
    daysOverdue: 2,
    season: 'recovering',
    special: 'christmas-tree',
  },

  // TERRACE - Empty / To-fill pots
  {
    id: 'pot-empty-1',
    name: 'Empty Pot',
    species: null,
    wall: 'corner-23',
    position: { x: 0.18, y: 0.12 },
    health: 'empty',
    emoji: '🪴',
    personality: null,
    container: 'Small white ribbed pot',
    lore: 'Waiting for something. The soil is ready.',
    poem: 'I am ready\nwhenever you are.',
    nextCare: 'Plant something',
    daysOverdue: 0,
    season: 'empty',
  },
  {
    id: 'pot-empty-2',
    name: 'Empty Pot',
    species: null,
    wall: 1,
    position: { x: 0.55, y: 0.93 },
    health: 'empty',
    emoji: '🪴',
    personality: null,
    container: 'Pink chalice ceramic (on table)',
    lore: 'A beautiful pot on the dining table. The last tenant did not survive winter.',
    poem: 'Pink and waiting.\nSomething cheerful\nwould be nice.',
    nextCare: 'Plant something',
    daysOverdue: 0,
    season: 'empty',
  },
  {
    id: 'pot-empty-3',
    name: 'Empty Pot',
    species: null,
    wall: 2,
    position: { x: 0.08, y: 0.52 },
    health: 'empty',
    emoji: '🪴',
    personality: null,
    container: 'White ceramic on mid-century legs',
    lore: 'The most stylish empty pot on the terrace. Deserves something equally stylish.',
    poem: 'My legs are beautiful.\nFill me with something worthy.',
    nextCare: 'Plant something',
    daysOverdue: 0,
    season: 'empty',
  },
  {
    id: 'pot-empty-4',
    name: 'Empty Pot',
    species: null,
    wall: 1,
    position: { x: 0.28, y: 0.93 },
    health: 'empty',
    emoji: '🪴',
    personality: null,
    container: 'White ribbed round (near grill)',
    lore: 'Near the grill. Waiting for spring.',
    poem: 'The grill smells like summer.\nI am ready for summer.',
    nextCare: 'Plant something',
    daysOverdue: 0,
    season: 'empty',
  },
  {
    id: 'pot-empty-5',
    name: 'Empty Pot',
    species: null,
    wall: 1,
    position: { x: 0.18, y: 0.93 },
    health: 'empty',
    emoji: '🪴',
    personality: null,
    container: 'Blue/slate ribbed round (near grill)',
    lore: 'Smaller but charming. Good for herbs or something with texture.',
    poem: 'Small but here.\nReady.',
    nextCare: 'Plant something',
    daysOverdue: 0,
    season: 'empty',
  },
  // Window sill
  {
    id: 'sill-left',
    name: 'Window Sill (Left)',
    species: null,
    wall: 1,
    position: { x: 0.62, y: 0.88 },
    health: 'empty',
    emoji: '🪴',
    personality: null,
    container: 'New planter (planned)',
    lore: 'The begonias that lived here did not survive last winter. Their memory is honored. New planters are planned.',
    poem: '† Begonia, 2024\nYou were colorful.\nYou are remembered.',
    nextCare: 'Get new planters',
    daysOverdue: 0,
    season: 'memorial',
    special: 'memorial',
  },
  {
    id: 'sill-right',
    name: 'Window Sill (Right)',
    species: null,
    wall: 1,
    position: { x: 0.72, y: 0.88 },
    health: 'empty',
    emoji: '🪴',
    personality: null,
    container: 'New planter (planned)',
    lore: 'The other begonia planter. Awaiting resurrection.',
    poem: '† Begonia, 2024\nSpring is coming.\nYou will be replaced with love.',
    nextCare: 'Get new planters',
    daysOverdue: 0,
    season: 'memorial',
    special: 'memorial',
  },
];

// FRONT PATCH PLANTS
export const FRONT_PLANTS = [
  {
    id: 'dko-1', name: "Double Knock Out Rose", species: 'Rosa "Double Knock Out"',
    position: { x: 0.2, y: 0.35 }, health: 'thriving', emoji: '🌹',
    lore: "Emma's Rose Garden. First planted last spring. Bulletproof roses — they bloom from May through frost and ask for almost nothing.",
    poem: 'I do not need your worry.\nI need your attention\nonce in a while.',
    nextCare: 'Neem oil in 2 weeks', daysOverdue: 0, season: 'dormant-waking',
  },
  {
    id: 'dko-2', name: "Double Knock Out Rose", species: 'Rosa "Double Knock Out"',
    position: { x: 0.35, y: 0.35 }, health: 'thriving', emoji: '🌹',
    lore: "One of six. Robust, red, reliable.",
    poem: 'Six of us.\nAll red.\nAll here.',
    nextCare: 'Neem oil in 2 weeks', daysOverdue: 0, season: 'dormant-waking',
  },
  {
    id: 'dko-3', name: "Double Knock Out Rose", species: 'Rosa "Double Knock Out"',
    position: { x: 0.5, y: 0.35 }, health: 'thriving', emoji: '🌹',
    lore: "Center front. Gets the most sun.",
    poem: 'Best spot in the garden.\nI did not ask for this.\nI am grateful anyway.',
    nextCare: 'Neem oil in 2 weeks', daysOverdue: 0, season: 'dormant-waking',
  },
  {
    id: 'dko-4', name: "Double Knock Out Rose", species: 'Rosa "Double Knock Out"',
    position: { x: 0.2, y: 0.6 }, health: 'thriving', emoji: '🌹',
    lore: "Back row, left.",
    poem: 'Back row.\nStill blooming.\nStill here.',
    nextCare: 'Neem oil in 2 weeks', daysOverdue: 0, season: 'dormant-waking',
  },
  {
    id: 'dko-5', name: "Double Knock Out Rose", species: 'Rosa "Double Knock Out"',
    position: { x: 0.5, y: 0.6 }, health: 'thriving', emoji: '🌹',
    lore: "Back row, center.",
    poem: 'We are six voices\nsaying the same red thing\nall summer long.',
    nextCare: 'Neem oil in 2 weeks', daysOverdue: 0, season: 'dormant-waking',
  },
  {
    id: 'dko-6', name: "Double Knock Out Rose", species: 'Rosa "Double Knock Out"',
    position: { x: 0.72, y: 0.5 }, health: 'thriving', emoji: '🌹',
    lore: "Right side, near the stoop.",
    poem: 'Near the door.\nEvery visitor sees me.\nI consider this a responsibility.',
    nextCare: 'Neem oil in 2 weeks', daysOverdue: 0, season: 'dormant-waking',
  },
  {
    id: 'worms',
    name: 'Worm Colony',
    species: 'Lumbricus terrestris',
    position: { x: 0.42, y: 0.7 },
    health: 'thriving',
    emoji: '🪱',
    lore: "The quiet workers of Emma's Rose Garden. Aerating, enriching, asking for nothing. More are planned.",
    poem: 'We have been here\nlonger than the roses.\nWe will be here after.',
    nextCare: 'Add more worms this spring',
    daysOverdue: 0, season: 'active',
  },
];

export const CARE_ACTIONS = [
  { id: 'water', label: 'Water', emoji: '💧', warmth: 10 },
  { id: 'fertilize', label: 'Fertilize', emoji: '🌿', warmth: 15 },
  { id: 'prune', label: 'Prune', emoji: '✂️', warmth: 15 },
  { id: 'neem', label: 'Neem Oil', emoji: '🛡️', warmth: 20 },
  { id: 'train', label: 'Train', emoji: '🪢', warmth: 25 },
  { id: 'repot', label: 'Repot', emoji: '🪣', warmth: 30 },
  { id: 'photo', label: 'Photograph', emoji: '📸', warmth: 15 },
  { id: 'visit', label: 'Just Visited', emoji: '👀', warmth: 5 },
];
